In [3]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np

hr_pw=[150, 425, 100, 375, 240]
mpg=[15, 42, 10, 37, 24]
acc=[300, 850, 200, 750, 480]
verdict=[4, 1, 5, 2, 3]
print("Horse power list = \n", hr_pw)
print("Minimun hr_pw = ", np.min(hr_pw))
print("Maximum hr_pw = ", np.max(hr_pw))

Horse power list = 
 [150, 425, 100, 375, 240]
Minimun hr_pw =  100
Maximum hr_pw =  425


In [4]:
hr_pw_arr=np.array(hr_pw)
mpg_arr=np.array(mpg)
verdict_arr=np.array(acc)
verdict_arr=np.array(verdict)
print("Horse power array = \n", hr_pw_arr)
print("Filter hr_pw = ", hr_pw_arr[np.where(hr_pw_arr>=300)])
print("Sorting hr_pw = ", np.sort(hr_pw_arr))
print("Mathematical operations on hr_pw - \n1. Sum = ", np.sum(hr_pw_arr), "\n2. Multiplication = ", np.multiply(hr_pw_arr[2],hr_pw_arr[4]))

Horse power array = 
 [150 425 100 375 240]
Filter hr_pw =  [425 375]
Sorting hr_pw =  [100 150 240 375 425]
Mathematical operations on hr_pw - 
1. Sum =  1290 
2. Multiplication =  24000


In [5]:
car_att=[[15, 42, 10, 37, 24],[150, 425, 100, 375, 240],[300, 850, 200, 750, 480],[4, 1, 5, 2, 3]]
car_att_arr=np.array(car_att)
print("Car attributes array = \n", car_att_arr)
print("Datatype of car_att_arr is ", car_att_arr.dtype)
print("Shape of car_att_arr is ", car_att_arr.shape)
print("Dimention of car_att_arr is ", car_att_arr.ndim)
print("To access an element - ", car_att_arr[2,1])
print("Different ways to access an multiple elements - \n1.", car_att_arr[0:4:1], "\n\n2.", car_att_arr[0:4:2,0:1], "\n\n3.", car_att_arr[0::4,0::1])

Car attributes array = 
 [[ 15  42  10  37  24]
 [150 425 100 375 240]
 [300 850 200 750 480]
 [  4   1   5   2   3]]
Datatype of car_att_arr is  int32
Shape of car_att_arr is  (4, 5)
Dimention of car_att_arr is  2
To access an element -  850
Different ways to access an multiple elements - 
1. [[ 15  42  10  37  24]
 [150 425 100 375 240]
 [300 850 200 750 480]
 [  4   1   5   2   3]] 

2. [[ 15]
 [300]] 

3. [[15 42 10 37 24]]


In [7]:
import micropip
await micropip.install("scipy")
from skimage.io import imread
from matplotlib import pyplot as plt

img=imread(Pictures/Infosys_ID_front.jpg)
plt.imshow(img)

<class 'NameError'>: name 'pip' is not defined